name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0, v1.0.1-beta, v2.1.0-rc, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if you're using Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or any version needed

      - name: Build project
        run: |
          npm install
          npm run build  # Customize this to fit your build process

      - name: Set release type (draft or pre-release)
        id: release_type
        run: |
          if [[ "${GITHUB_REF}" == *"-beta"* || "${GITHUB_REF}" == *"-alpha"* || "${GITHUB_REF}" == *"-rc"* ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Zip dist folder (make sure it exists)
        run: |
          if [ -d "dist" ]; then
            zip -r dist.zip dist/
          else
            echo "dist folder not found, skipping zip step."
          fi

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            ## Changes
            - Add release notes here.

          draft: false
          prerelease: ${{ env.prerelease }}

      - name: Upload build artifact
        if: success() && steps.zip.outputs.zip-path  # Check if zip step succeeded
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist.zip