name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on tags like v1.0.0, v1.0.1-beta, v2.1.0-rc, etc.

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if you're using Node.js)
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # or any version needed

      - name: Build project
        id: build
        run: |
          npm install
          npm run build  # Customize this to fit your build process

      - name: Set release type (draft or pre-release)
        id: release_type
        run: |
          if [[ "${GITHUB_REF}" == *"-beta"* || "${GITHUB_REF}" == *"-alpha"* || "${GITHUB_REF}" == *"-rc"* ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Zip dist folder (make sure it exists)
        id: zip
        run: |
          if [ -d "dist" ]; then
            zip -r dist.zip dist/
          else
            echo "dist folder not found, skipping zip step."
          fi

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}  # Corrected to use only the tag name
          name: Release ${{ github.ref_name }}  # Consistent naming
          body: |
            ## Changes
            - Add release notes here.
          draft: false
          prerelease: ${{ env.prerelease }}
          files: dist.zip  # Attach the zipped dist folder as a release asset
